apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  labels:
    pv: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /home/data
    server: 192.168.140.141
