name: dubbo
imageRegistry_admin: 10.0.160.9:5000/dubbo:admin
imageRegistry_zookeeper: 10.0.160.9:5000/dubbo:zookeeper
imageRegistry_producer: 10.0.160.9:5000/dubbo:producer
imageRegistry_consumer: 10.0.160.9:5000/dubbo:consumer

